spring:
  application:
    name: CappsNews

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

  docker:
    compose:
      enabled: false

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5433/cappsnews
    username: cappsnews
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 76cc5b64379b7e
    password: 5ef7cf5224a202
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs

jwt:
  secret:
    key: 9j3hYtrVTWihkQs73f7ikrycNPSjUIFcSkQPgVUjRKGCHYLFI2qCn4xhAFYhTfvm

cors:
  allowed-origins: http://localhost:4200

logging:
  level:
    org.springframework.web.filter.CorsFilter: DEBUG
    org:
      springframework:
        security: TRACE



cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
application:
  bucket:
    name: ${APP_BUCKET_NAME}




server:
  port: 8081