version: '3.8'

services:
  postgres:
    image: 'postgres:17'
    container_name: cappsnews_db
    environment:
      POSTGRES_USER: cappsnews
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cappsnews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
